<a href="https://colab.research.google.com/github/juan0898/BackendEstudiantes/blob/main/Te_damos_la_bienvenida_a_Colaboratory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
from google.colab import files
files.upload()

Saving ventas_empresa_online.csv to ventas_empresa_online.csv

{'ventas_empresa_online.csv': b'\xef\xbb\xbfid_pedido,fecha,hora,id_cliente,segmento_cliente,ciudad,departamento,canal_venta,producto,categoria,cantidad,precio_unitario,descuento_pct,costo_envio,subtotal,total_pagado,metodo_pago,estado_pedido,dias_entrega,calificacion,devuelto\nORD-00001,2026-01-01,10:59,CLI-00694,Nuevo,Pereira,Risaralda,Marketplace,Crema facial,Cuidado personal,1,74000,20,0,74000,59200.0,Tarjeta cr\xc3\xa9dito,Enviado,,,No\nORD-00002,2026-05-13,13:32,CLI-00102,Recurrente,Bogot\xc3\xa1,Cundinamarca,Marketplace,Aud\xc3\xadfonos Bluetooth,Tecnolog\xc3\xada,2,89000,25,12000,178000,145500.0,Daviplata,Devuelto,3.0,2.0,S\xc3\xad\nORD-00003,2026-01-23,17:50,CLI-00385,Corporativo,Pereira,Risaralda,Instagram,Banda el\xc3\xa1stica fitness,Deportes,1,45000,20,8000,45000,44000.0,Nequi,Entregado,6.0,4.0,No\nORD-00004,2026-02-23,22:03,CLI-00754,VIP,Manizales,Caldas,Web,Webcam HD,Tecnolog\xc3\xada,1,120000,0,0,120000,120000.0,PSE,Entregado,3.0,4.0,No\nORD-00005,2026-04-06,18:24,CLI-00607,Nuevo,Bogot\xc3\xa1,Cundinamarca,Marketplace,Webcam HD,Tecnolog\xc3\xada,1,120000,0,10000,120000,130000.0,Tarjeta cr\xc3\xa9dito,Entregado,1.0,4.0,No\nORD-00006,2026-06-10,19:59,CLI-00567,VIP,Ibagu\xc3\xa9,Tolima,Instagram,Kit de barber\xc3\xada,Cuidado personal,1,132000,10,15000,132000,133800.0,PSE,En preparaci\xc3\xb3n,,,No\nORD-00007,2026-02-28,15:11,CLI-00325,Nuevo,Villavicencio,Meta,Web,Soporte para port\xc3\xa1til,Oficina,1,87000,5,15000,87000,97650.0,Tarjeta d\xc3\xa9bito,Entregado,1.0,5.0,No\nORD-00008,2026-04-15,06:15,CLI-00227,Recurrente,bucaramanga,Santander,Marketplace,Soporte para port\xc3\xa1til,Oficina,1,82000,0,0,82000,82000.0,Tarjeta d\xc3\xa9bito,Cancelado,,,No\nORD-00009,2026-01-27,19:55,CLI-00210,Corporativo,Villavicencio,Meta,Web,Crema facial,Cuidado personal,1,69000,0,0,69000,69000.0,PSE,Entregado,5.0,5.0,No\nORD-00010,2026-08-07,11:37,CLI-00403,Recurrente, NEIVA ,Huila,Web,Banda el\xc3\xa1stica fitness,Deportes,1,48000,10,0,48000,43200.0,Daviplata,Entregado,3.0,5.5,No\nORD-00011,2026-05-27,08:43,CLI-00543,Nuevo,Barranquilla,Atl\xc3\xa1ntico,Web,Tapete de yoga,Deportes,4,95000,5,12000,380000,373000.0,Daviplata,Entregado,1.0,5.0,No\nORD-00012,2026-03-28,10:04,CLI-00494,Nuevo,Manizales,Caldas,Marketplace,L\xc3\xa1mpara LED escritorio,Hogar,3,73000,0,8000,219000,227000.0,Contraentrega,Entregado,6.0,3.0,No\nORD-00013,2026-04-23,13:30,CLI-00092,Recurrente,Pereira,Risaralda,Web,Parlante port\xc3\xa1til,Tecnolog\xc3\xada,1,145000,0,8000,145000,153000.0,PSE,Entregado,4.0,5.0,No\nORD-00014,2026-03-30,22:42,CLI-00379,VIP,Manizales,Caldas,Instagram,Cable USB-C,Tecnolog\xc3\xada,1,27000,0,8000,27000,35000.0,Contraentrega,Entregado,4.0,4.0,No\nORD-00015,2026-08-07,19:53,CLI-00610,VIP,Villavicencio,Meta,Marketplace,Smartwatch,Tecnolog\xc3\xada,1,245000,5,0,245000,232750.0,Daviplata,Entregado,3.0,5.0,No\nORD-00016,2026-02-16,23:32,CLI-00633,Corporativo,Cartagena,Bol\xc3\xadvar,Instagram,Juego de s\xc3\xa1banas,Hogar,1,112000,0,0,112000,112000.0,Contraentrega,Entregado,3.0,5.0,No\nORD-00017,2026-08-10,07:21,CLI-00013,VIP,Bogot\xc3\xa1,Cundinamarca,App m\xc3\xb3vil,Agenda ejecutiva,Oficina,1,42000,25,15000,42000,46500.0,Tarjeta cr\xc3\xa9dito,Entregado,5.0,4.0,No\nORD-00018,2026-07-01,16:00,CLI-00331,Recurrente,Cali,Valle del Cauca,App m\xc3\xb3vil,Organizador modular,Hogar,1,63000,20,0,63000,50400.0,PSE,Entregado,3.0,4.0,No\nORD-00019,2026-05-09,20:11,CLI-00832,Corporativo,Neiva,Huila,App m\xc3\xb3vil,Soporte para port\xc3\xa1til,Oficina,-1,-1,10,15000,87000,93300.0,Nequi,Entregado,3.0,5.0,No\nORD-00020,2026-03-30,21:39,CLI-00063,Recurrente,Cali,Valle del Cauca,Instagram,Organizador modular,Hogar,1,55000,15,10000,55000,56750.0,PSE,Entregado,4.0,5.0,No\nORD-00021,2026-05-03,15:08,CLI-00755,Corporativo,Medell\xc3\xadn,Antioquia,App m\xc3\xb3vil,Smartwatch,Tecnolog\xc3\xada,2,242000,0,10000,484000,494000.0,Tarjeta d\xc3\xa9bito,Entregado,2.0,4.0,No\nORD-00022,2026-08-31,20:47,CLI-00560,VIP,Barranquilla,Atl\xc3\xa1ntico,Marketplace,Aud\xc3\xadfonos Bluetooth,Tecnolog\xc3\xada,1,94000,0,12000,94000,106000.0,Tarjeta cr\xc3\xa9dito,En preparaci\xc3\xb3n,,,No\nORD-00023,2026-03-28,21:23,CLI-00424,Nuevo,Cartagena,Bol\xc3\xadvar,App m\xc3\xb3vil,Webcam HD,Tecnolog\xc3\xada,1,98.000,5,15000,128000,136600.0,Daviplata,Entregado,2.0,5.0,No\nORD-00024,2026-07-03,23:49,CLI-00909,Nuevo,Pereira,Risaralda,Marketplace,Crema facial,Cuidado personal,1,71000,0,0,71000,71000.0,PSE,Entregado,3.0,5.0,No\nORD-00025,2026-02-04,09:45,CLI-00746,Corporativo,Cali,Valle del Cauca,Instagram,Tapete de yoga,Deportes,2,100000,0,15000,200000,5000000,Daviplata,Entregado,5.0,5.0,No\nORD-00026,2026-04-10,23:27,CLI-00328,Corporativo,Pasto,Nari\xc3\xb1o,App m\xc3\xb3vil,Memoria USB 64GB,Tecnolog\xc3\xada,1,47000,25,12000,47000,47250.0,Daviplata,Cancelado,,,No\nORD-00027,2026-06-06,10:45,CLI-00703,VIP,Villavicencio,Meta,App m\xc3\xb3vil,Botella t\xc3\xa9rmica,Hogar,1,67000,10,15000,67000,75300.0,Nequi,Cancelado,2,5,S\xc3\xad\nORD-00028,2026-08-30,06:05,CLI-00883,Recurrente,Bogot\xc3\xa1,Cundinamarca,Marketplace,Organizador modular,Hogar,1,53000,20,0,53000,42400.0,Tarjeta cr\xc3\xa9dito,Enviado,,,No\nORD-00029,2026-08-14,14:06,CLI-00499,VIP,Villavicencio,Meta,Web,Soporte para port\xc3\xa1til,Oficina,1,87000,5,15000,87000,97650.0,Tarjeta d\xc3\xa9bito,Entregado,4.0,4.0,No\nORD-00030,2026-01-07,12:44,CLI-00402,Nuevo,Neiba,Huila,Marketplace,Power Bank 10000mAh,Tecnolog\xc3\xada,1,95000,0,10000,95000,105000.0,PSE,En preparaci\xc3\xb3n,,,No\nORD-00031,2026-06-24,19:02,CLI-00492,VIP,Villavicencio,Meta,Marketplace,Soporte para port\xc3\xa1til,Oficina,1,87000,0,15000,87000,102000.0,PSE,Entregado,5.0,5.0,No\nORD-00032,2026-06-02,22:30,CLI-00069,Nuevo,Bogot\xc3\xa1,Cundinamarca,App m\xc3\xb3vil,Parlante port\xc3\xa1til,Tecnolog\xc3\xada,1,145000,10,0,145000,130500.0,Nequi,Cancelado,,,No\nORD-00033,2026-08-16,17:42,CLI-00013,VIP,Pereira,Risaralda,Web,Memoria 64 GB,Tecnolog\xc3\xada,1,52000,0,10000,52000,0,Tarjeta cr\xc3\xa9dito,Devuelto,3.0,3.0,S\xc3\xad\nORD-00034,2026-01-27,06:39,CLI-00946,Nuevo,Barranquilla,Atl\xc3\xa1ntico,Instagram,Banda el\xc3\xa1stica fitness,Deportes,3,51000,15,0,153000,130050.0,Tarjeta d\xc3\xa9bito,Entregado,7.0,5.0,No\nORD-00035,2026-07-30,16:54,CLI-00680,Nuevo,Medell\xc3\xadn,Antioquia,Instagram,Silla ergon\xc3\xb3mica,Oficina,2,485000,0,0,970000,970000.0,Daviplata,Entregado,1.0,5.0,No\nORD-00036,2026-07-02,22:40,CLI-00824,Recurrente,Medell\xc3\xadn,Antioquia,App m\xc3\xb3vil,Parlante port\xc3\xa1til,Tecnolog\xc3\xada,1,148000,0,0,148000,148000.0,Tarjeta cr\xc3\xa9dito,Entregado,5.0,4.0,No\nORD-00037,2026-07-17,12:32,CLI-00091,Corporativo,Villavicencio,Meta,Marketplace,Agenda ejecutiva,Oficina,1,45000,0,12000,45000,57000.0,Nequi,Entregado,4.0,2.0,No\nORD-00038,2026-06-05,19:50,CLI-00058,Corporativo,Cali,Valle del Cauca,App m\xc3\xb3vil,Secador de cabello,Cuidado personal,1,150000,0,8000,150000,158000.0,Tarjeta d\xc3\xa9bito,Cancelado,,,No\nORD-00039,2026-06-18,21:33,CLI-00744,Recurrente,Bogot\xc3\xa1,Cundinamarca,Marketplace,Soporte para port\xc3\xa1til,Oficina,3,87000,20,0,261000,208800.0,Contraentrega,Entregado,2.0,4.0,No\nORD-00040,2026-04-12,15:43,CLI-00251,Nuevo,Medell\xc3\xadn,Antioquia,Marketplace,Cable USB-C,Tecnolog\xc3\xada,1,37000,0,12000,37000,49000.0,Nequi,En preparaci\xc3\xb3n,,,No\nORD-00041,,17:32,CLI-00714,Corporativo,Barranquilla,Atl\xc3\xa1ntico,Instagram,Silla ergon\xc3\xb3mica,Oficina,1,485000,0,12000,485000,497000.0,Daviplata,Entregado,4.0,4.0,No\nORD-00042,2026-04-07,18:32,CLI-00718,Nuevo,Pasto,Nari\xc3\xb1o,Marketplace,Aud\xc3\xadfonos Bluetooth,Tecnolog\xc3\xada,1,89000,20,10000,89000,81200.0,PSE,Entregado,6.0,4.0,No\nORD-00043,2026-08-08,07:54,CLI-00061,Nuevo,Bogot\xc3\xa1,Cundinamarca,Instagram,L\xc3\xa1mpara LED escritorio,Hogar,1,81000,0,10000,81000,91000.0,Daviplata,Enviado,,,No\nORD-00044,2026-07-23,15:40,CLI-00526,Nuevo,Bogot\xc3\xa1,Cundinamarca,Web,Smartwatch,Tecnolog\xc3\xada,1,245000,5,15000,245000,247750.0,Daviplata,Entregado,3.0,3.0,No\nORD-00045,2026-07-14,20:05,CLI-00375,Corporativo,Manizales,Caldas,App m\xc3\xb3vil,Parlante port\xc3\xa1til,Tecnolog\xc3\xada,2,145000,0,10000,290000,9999,Nequi,Entregado,2.0,5.0,No\nORD-00046,2026-03-21,09:19,CLI-00885,Corporativo,Villavicencio,Meta,Instagram,Agenda ejecutiva,Oficina,1,37000,0,15000,37000,52000.0,PSE,Entregado,6.0,5.0,No\nORD-00047,2026-04-23,06:57,CLI-00294,VIP,Barranquilla,Atl\xc3\xa1ntico,App m\xc3\xb3vil,Secador de cabello,Cuidado personal,1,158000,5,15000,158000,165100.0,Daviplata,Entregado,5.0,5.0,No\nORD-00048,2026-06-13,06:19,CLI-00751,VIP,Bucaramanga,Santander,Instagram,L\xc3\xa1mpara LED escritorio,Hogar,1 unidad,76000,0,10000,76000,86000.0,Daviplata,Devuelto,5.0,2.0,S\xc3\xad\nORD-00049,2026-04-09,09:09,CLI-00844,Corporativo,Bucaramanga,Santander,Marketplace,L\xc3\xa1mpara LED escritorio,Hogar,1,73000,15,8000,73000,70050.0,Tarjeta cr\xc3\xa9dito,En preparaci\xc3\xb3n,,,No\nORD-00050,2026-08-24,23:20,CLI-00740,Recurrente,Pereira,Risaralda,Instagram,Banda el\xc3\xa1stica fitness,Deportes,1,48000,10,8000,48000,51200.0,PSE,Entregado,3.0,5.0,No\nORD-00051,2026-07-28,08:41,CLI-00170,Corporativo,Cartagena,Bol\xc3\xadvar,Web,Mancuernas 5kg,Deportes,1,132000,15,10000,132000,122200.0,Nequi,Entregado,6.0,3.0,No\nORD-00052,2026-08-29,11:51,CLI-00851,Recurrente,,,,,,,,0,10000,132000,142000.0,,Devuelto,8.0,3.0,S\xc3\xad\nORD-00053,2026-07-14,08:43,CLI-00216,Corporativo,Ibagu\xc3\xa9,Tolima,Instagram,L\xc3\xa1mpara LED escritorio,Hogar,1,73000,0,8000,73000,81000.0,Tarjeta cr\xc3\xa9dito,Enviado,,,No\nORD-00054,2026-05-20,22:24,CLI-00547,Recurrente,Pereira,Risaralda,Web,Silla ergon\xc3\xb3mica,Oficina,1,482000,25,15000,482000,376500.0,PSE,Entregado,3.0,3.0,No\nORD-00055,2026-08-12,06:31,CLI-00303,Recurrente,Medell\xc3\xadn,Antioquia,Instagram,Memoria USB 64GB,Tecnolog\xc3\xada,1,52000,0,10000,52000,62000.0,Contraentrega,En preparaci\xc3\xb3n,,,No\nORD-00056,2026-07-05,14:36,CLI-00680,Nuevo,Bogot\xc3\xa1,Cundinamarca,Web,Banda el\xc3\xa1stica fitness,Deportes,1,48000,0,15000,48000,63000.0,Contraentrega,Entregado,4.0,,No\nORD-00057,2026-06-15,22:29,CLI-00484,Corporativo,Bucaramanga,Santander,Marketplace,L\xc3\xa1mpara LED escritorio,Hogar,1,76000,0,8000,76000,84000.0,Tarjeta cr\xc3\xa9dito,Entregado,3.0,5.0,No\nORD-00058,2026-05-26,13:58,CLI-00647,Corporativo,Ibagu\xc3\xa9,Tolima,Instagram,Smartwatch,Tecnolog\xc3\xada,1,245000,0,8000,245000,253000.0,Nequi,Entregado,4.0,5.0,No\nORD-00059,2026-05-22,22:48,CLI-00502,VIP,Bucaramanga,Santander,App m\xc3\xb3vil,Power Bank 10000mAh,Tecnolog\xc3\xada,1,95000,25,0,95000,71250.0,Nequi,Entregado,5.0,5.0,No\nORD-00060,2026-08-10,20:02,CLI-00144,Recurrente,Bucaramanga,Santander,Instagram,Cable USB-C,Tecnolog\xc3\xada,1,32000,10,0,32000,28800.0,Contraentrega,Entregado,3.0,5.0,No\nORD-00061,2026-06-27,06:41,CLI-00917,Corporativo,Villavicencio,Meta,Instagram,Agenda ejecutiva,Oficina,2,42000,0,0,84000,84000.0,Tarjeta d\xc3\xa9bito,Entregado,2.0,5.0,No\nORD-00062,2026-01-30,18:23,CLI-00163,,Cartagena,Bol\xc3\xadvar,Instagram,Agenda ejecutiva,Oficina,1,39000,0,10000,39000,49000.0,Tarjeta cr\xc3\xa9dito,Entregado,5.0,3.0,No\nORD-00063,2026-07-31,23:59,CLI-00950,Corporativo,Villavicencio,Meta,App m\xc3\xb3vil,Tapete de yoga,Deportes,1,95000,0,10000,95000,105000.0,Tarjeta cr\xc3\xa9dito,Entregado,1.0,3.0,No\nORD-00064,2026-03-19,07:39,CLI-00236,Corporativo,Barranquilla,Atl\xc3\xa1ntico,Marketplace,Secador de cabello,Cuidado personal,1,155000,0,8000,155000,163000.0,T. credito,Enviado,,,No\nORD-00065,2026-01-02,10:32,CLI-00427,Corporativo,Villavicencio,Meta,Web,Webcam HD,Tecnolog\xc3\xada,1,120000,0,8000,120000,128000.0,Daviplata,Enviado,,,No\nORD-00066,2026/99/99,10:59,CLI-00589,VIP,Villavicencio,Meta,Instagram,Memoria USB 64GB,Tecnolog\xc3\xada,1,52000,20,12000,52000,53600.0,Tarjeta cr\xc3\xa9dito,Entregado,5.0,5.0,No\nORD-00067,2026-02-14,22:08,CLI-00496,Corporativo,Bucaramanga,Santander,Marketplace,Power Bank 10000mAh,Tecnolog\xc3\xada,1,98000,0,15000,98000,113000.0,Tarjeta d\xc3\xa9bito,Enviado,,,No\nORD-00068,2026-06-22,23:51,CLI-00809,VIP,Bogot\xc3\xa1,Cundinamarca,Instagram,Crema facial,Cuidado personal,1,74000,0,12000,74000,86000.0,Tarjeta d\xc3\xa9bito,Entregado,3.0,4.0,No\nORD-00069,2026-06-02,19:58,CLI-00575,VIP,Barranquilla,Atl\xc3\xa1ntico,Instagram,Aud\xc3\xadfonos Bluetooth,Tecnolog\xc3\xada,1,94000,5,0,94000,89300.0,PSE,Entregado,7.0,5.0,No\nORD-00070,2026-04-16,16:28,CLI-00292,VIP,Ibagu\xc3\xa9,Tolima,App m\xc3\xb3vil,Cafetera el\xc3\xa9ctrica,Hogar,1,188000,0,10000,188000,198000.0,Tarjeta d\xc3\xa9bito,Entregado,1.0,4.0,No\nORD-00071,2026-01-27,22:54,CLI-00493,Corporativo,Pasto,Nari\xc3\xb1o,Instagram,Botella t\xc3\xa9rmica,,2,62000,0,12000,124000,136000.0,PSE,Entregado,1.0,4.0,No\nORD-00072,2026-05-28,12:46,CLI-00432,Corporativo,Bogot\xc3\xa1,Cundinamarca,App m\xc3\xb3vil,Cafetera el\xc3\xa9ctrica,Hogar,1,185000,0,0,185000,185000.0,Tarjeta cr\xc3\xa9dito,Entregado,1.0,4.0,No\nORD-00073,2026-06-25,08:38,CLI-00523,Corporativo,Pasto,Nari\xc3\xb1o,Marketplace,L\xc3\xa1mpara LED escritorio,Hogar,2,76000,0,15000,152000,167000.0,PSE,Entregado,3.0,5.0,No\nORD-00074,2026-01-16,19:28,CLI-00039,Corporativo,,Nari\xc3\xb1o,App m\xc3\xb3vil,Webcam HD,Tecnolog\xc3\xada,2,130000,0,0,260000,260000.0,Tarjeta d\xc3\xa9bito,Entregado,4.0,4.0,No\nORD-00075,2026-07-10,16:52,CLI-00802,Recurrente,Neiva,Huila,App m\xc3\xb3vil,Silla ergon\xc3\xb3mica,Oficina,3,490000,0,12000,1470000,1482000.0,Nequi,Entregado,2.0,4.0,No\nORD-00076,2026-05-05,20:34,CLI-00295,VIP,Pereira,Risaralda,Marketplace,Kit de barber\xc3\xada,Cuidado personal,1,129000,5,0,129000,122550.0,Daviplata,Enviado,,,No\nORD-00077,2026-05-29,20:16,CLI-00473,VIP,Villavicencio,Meta,Marketplace,Cafetera el\xc3\xa9ctrica,Hogar,1,190000,10,15000,190000,186000.0,Nequi,Enviado,,,No\nORD-00078,2026-08-24,14:56,CLI-00118,Nuevo,Cali,Valle del Cauca,App m\xc3\xb3vil,Aud\xc3\xadfonos Bluetooth,Tecnolog\xc3\xada,1,89000,25,10000,89000,76750.0,Tarjeta d\xc3\xa9bito,Enviado,,,No\nORD-00079,2026-05-05,22:57,CLI-00385,Corporativo,Bogot\xc3\xa1,Cundinamarca,Instagram,Aud\xc3\xadfonos Bluetooth,Tecnolog\xc3\xada,1,84000,5,8000,84000,87800.0,Tarjeta d\xc3\xa9bito,Entregado,2.0,3.0,No\nORD-00080,2026-03-31,22:05,CLI-00897,Nuevo,Cartagena,Bol\xc3\xadvar,Marketplace,Morral deportivo,Deportes,1,,20,8000,118000,102400.0,Tarjeta cr\xc3\xa9dito,Entregado,4.0,4.0,No\nORD-00081,2026-05-13,23:29,CLI-00224,Corporativo,Barranquilla,Atl\xc3\xa1ntico,Marketplace,Tapete de yoga,Deportes,1,95000,0,0,95000,95000.0,Daviplata,Entregado,4.0,2.0,No\nORD-00082,2026-05-23,13:05,CLI-00718,Nuevo,Bucaramanga,Santander,App m\xc3\xb3vil,Tapete de yoga,Deportes,2,95000,0,8000,190000,198000.0,Tarjeta cr\xc3\xa9dito,Entregado,5.0,5.0,No\nORD-00083,2026-03-28,17:01,CLI-00716,Corporativo,Bucaramanga,Santander,Instagram,Soporte para port\xc3\xa1til,Oficina,2,87000,0,12000,174000,186000.0,PSE,Enviado,,,No\nORD-00084,2026-07-18,23:19,CLI-00193,Corporativo,Villavicencio,Meta,Web,Teclado mec\xc3\xa1nico,Tecnolog\xc3\xada,2,168000,0%,8000,336000,344000.0,Tarjeta d\xc3\xa9bito,En preparaci\xc3\xb3n,,,No\nORD-00085,2026-08-18,15:31,CLI-00256,Corporativo,Bogot\xc3\xa1,Cundinamarca,App m\xc3\xb3vil,Agenda ejecutiva,Oficina,1,42000,0,0,42000,42000.0,Tarjeta cr\xc3\xa9dito,Entregado,1.0,3.0,No\nORD-00086,2026-05-19,06:52,CLI-00608,Corp.,Cartagena,Bol\xc3\xadvar,Web,Kit de barber\xc3\xada,Cuidado personal,2,132000,0,12000,264000,276000.0,Daviplata,Entregado,2.0,3.0,No\nORD-00087,2026-03-07,14:46,CLI-00048,Nuevo,Bucaramanga,Santander,Instagram,Cable USB-C,Tecnolog\xc3\xada,1,32000,0,15000,32000,47000.0,Nequi,Entregado,3.0,2.0,No\nORD-00088,2026-07-09,23:36,CLI-00266,VIP,Barranquilla,Atl\xc3\xa1ntico,Instagram,Aud\xc3\xadfonos Bluetooth,Tecnolog\xc3\xada,1,84000,0,N/A,84000,92000.0,PSE,Entregado,5.0,5.0,No\nORD-00089,2026-05-27,11:08,CLI-00113,Recurrente,Bucaramanga,Risaralda,App m\xc3\xb3vil,Teclado mec\xc3\xa1nico,Tecnolog\xc3\xada,1,165000,20,15000,165000,147000.0,PSE,Entregado,5.0,5.0,No\nORD-00090,2026-05-22,17:45,CLI-00054,Corporativo,Medell\xc3\xadn,Antioquia,Marketplace,Organizador modular,Hogar,2,58000,20,12000,116000,104800.0,PSE,entregado,4.0,5.0,No\nORD-00091,2026-05-16,18:10,CLI-00342,Nuevo,Ibagu\xc3\xa9,Tolima,Instagram,Power Bank 10000mAh,Tecnolog\xc3\xada,1,98000,15,15000,98000,98300.0,Nequi,Entregado,3.0,5.0,No\nORD-00092,2026-08-22,16:25,CLI-00674,Nuevo,Barranquilla,Atl\xc3\xa1ntico,App m\xc3\xb3vil,Morral deportivo,Deportes,1,118000,0,0,118000,118000.0,Nequi, ENVIADO ,,,No\nORD-00093,2026-03-07,10:43,CLI-00246,Nuevo,Manizales,Caldas,Marketplace,Power Bank 10000mAh,Tecnolog\xc3\xada,1,103000,15,0,103000,87550.0,Tarjeta cr\xc3\xa9dito,Entregado,4.0,1.0,No\nORD-00094,2026-03-16,13:28,CLI-00014,Corporativo,Barranquilla,Atl\xc3\xa1ntico,Web,Organizador modular,Hogar,1,61000,25,10000,61000,55750.0,Tarjeta cr\xc3\xa9dito,Entregado,2.0,4.0,No\nORD-00095,2026-07-19,08:19,CLI-00860,VIP,Barranquilla,Atl\xc3\xa1ntico,Instagram,Silla ergon\xc3\xb3mica,Oficina,1,8500000,25,8000,480000,368000.0,Contraentrega,Entregado,5.0,4.0,No\nORD-00096,2026-07-22,06:35,CLI-00412,Corporativo,Bucaramanga,Santander,Web,L\xc3\xa1mpara LED escritorio,Hogar,-5,76000,0,0,76000,76000.0,Daviplata,Devuelto,5.0,3.0,S\xc3\xad\nORD-00097,2026-02-13,16:24,CLI-00106,Nuevo,Villavicencio,Meta,Instagram,Aud\xc3\xadfonos Bluetooth,Tecnolog\xc3\xada,2,89000,10,12000,178000,172200.0,Daviplata,Entregado,6.0,5.0,No\nORD-00098,2026-02-21,12:20,CLI-00528,Recurrente,Bucaramanga,Santander,App m\xc3\xb3vil,Teclado mec\xc3\xa1nico,Tecnolog\xc3\xada,1,165000,0,0,165000,165000.0,Tarjeta cr\xc3\xa9dito,Entregado,6.0,2.0,No\nORD-00099,2026-04-19,15:32,CLI-00256,Recurrente,Bucaramanga,Santander,Marketplace,Producto sorpresa,Oficina,1,42000,20,8000,42000,41600.0,Contraentrega,Enviado,,,No\nORD-00100,2026-07-17,09:59,CLI-00823,VIP,Bogot\xc3\xa1,Cundinamarca,App m\xc3\xb3vil,Secador de cabello,Cuidado personal,1,152000,0,10000,152000,162000.0,Contraentrega,Enviado,,,No\nORD-00101,2026-06-19,08:25,CLI-00782,Nuevo,Bogot\xc3\xa1,Cundinamarca,Web,Aud\xc3\xadfonos Bluetooth,Tecnolog\xc3\xada,1,84000,0,15000,84000,99000.0,Contraentrega,Entregado,2.0,4.0,No\nORD-00102,2026-06-21,11:41,CLI-00570,VIP,,Bol\xc3\xadvar,Instagram,Aud\xc3\xadfonos Bluetooth,Tecnolog\xc3\xada,1,94000,0,10000,94000,104000.0,Nequi,Entregado,8.0,5.0,No\nORD-00103,2026-02-06,11:25,CLI-00705,VIP,Bucaramanga,Santander,Web,Silla ergon\xc3\xb3mica,Oficina,1,485000,0,0,485000,485000.0,Tarjeta cr\xc3\xa9dito,Devuelto,4.0,2.0,S\xc3\xad\nORD-00104,2026-08-31,19-30,CLI-00312,Corporativo,Ibagu\xc3\xa9,Tolima,Instagram,Soporte para port\xc3\xa1til,Oficina,1,82000,0,0,82000,82000.0,Tarjeta cr\xc3\xa9dito,Entregado,4.0,5.0,No\nORD-00105,2026-07-25,22:27,CLI-00782,VIP,Cali,Valle del Cauca,Web,Parlante port\xc3\xa1til,Tecnolog\xc3\xada,1,148000,0,15000,148000,163000.0,Tarjeta d\xc3\xa9bito,Entregado,3.0,4.0,No\nORD-00106,2026-06-12,13:46,CLI-999999,Nuevo,Ibagu\xc3\xa9,Tolima,App m\xc3\xb3vil,Cafetera el\xc3\xa9ctrica,Hogar,1,185000,25,15000,185000,153750.0,PSE,Enviado,,,No\nORD-00107,2026-06-20,20:22,CLI-00092,Nuevo,Pasto,Nari\xc3\xb1o,Web,Aud\xc3\xadfonos Bluetooth,Tecnolog\xc3\xada,1,84000,0,10000,84000,94000.0,Nequi,Entregado,5.0,3.0,No\nORD-00108,2026-07-10,07:02,CLI-00232,Nuevo,Medell\xc3\xadn,Antioquia,App m\xc3\xb3vil,Power Bank 10000mAh,Tecnolog\xc3\xada,1,98000,0,0,98000,98000.0,Daviplata,Entregado,3.0,5.0,No\nORD-00109,2026-02-28,19:47,CLI-00914,VIP,Ibagu\xc3\xa9,Tolima,Web,Agenda ejecutiva,Oficina,1,42000,10,15000,42000,52800.0,Nequi,En preparaci\xc3\xb3n,,,No\nORD-00110,2026-04-10,17:43,CLI-00281,Nuevo,Medell\xc3\xadn,Antioquia,Instagram,Soporte para port\xc3\xa1til,Oficina,1,87000,0,10000,87000,97000.0,Tarjeta d\xc3\xa9bito,Entregado,3.0,4.0,No\nORD-00111,2026-07-14,20:52,CLI-00432,Corporativo,Neiva,Huila,Marketplace,Secador de cabello,Cuidado personal,4,155000,0,8000,620000,628000.0,Daviplata,En preparaci\xc3\xb3n,,,No\nORD-00112,2026-06-29,07:24,CLI-00624,Nuevo,Medell\xc3\xadn,Antioquia,Instagram,Botella t\xc3\xa9rmica,Hogar,1,67000,1

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [8]:
df = pd.read_csv("ventas_empresa_online.csv")

In [9]:
df.head()

,id_pedido,fecha,hora,id_cliente,segmento_cliente,ciudad,departamento,canal_venta,producto,categoria,...,precio_unitario,descuento_pct,costo_envio,subtotal,total_pagado,metodo_pago,estado_pedido,dias_entrega,calificacion,devuelto
0,ORD-00001,2026-01-01,10:59,CLI-00694,Nuevo,Pereira,Risaralda,Marketplace,Crema facial,Cuidado personal,...,74000,20,0,74000,59200.0,Tarjeta crédito,Enviado,NaN,NaN,No
1,ORD-00002,2026-05-13,13:32,CLI-00102,Recurrente,Bogotá,Cundinamarca,Marketplace,Audífonos Bluetooth,Tecnología,...,89000,25,12000,178000,145500.0,Daviplata,Devuelto,3.0,2.0,Sí
2,ORD-00003,2026-01-23,17:50,CLI-00385,Corporativo,Pereira,Risaralda,Instagram,Banda elástica fitness,Deportes,...,45000,20,8000,45000,44000.0,Nequi,Entregado,6.0,4.0,No
3,ORD-00004,2026-02-23,22:03,CLI-00754,VIP,Manizales,Caldas,Web,Webcam HD,Tecnología,...,120000,0,0,120000,120000.0,PSE,Entregado,3.0,4.0,No
4,ORD-00005,2026-04-06,18:24,CLI-00607,Nuevo,Bogotá,Cundinamarca,Marketplace,Webcam HD,Tecnología,...,120000,0,10000,120000,130000.0,Tarjeta crédito,Entregado,1.0,4.0,No

In [10]:
df.shape

(1849, 21)

In [11]:
df.columns

Index(['id_pedido', 'fecha', 'hora', 'id_cliente', 'segmento_cliente',
       'ciudad', 'departamento', 'canal_venta', 'producto', 'categoria',
       'cantidad', 'precio_unitario', 'descuento_pct', 'costo_envio',
       'subtotal', 'total_pagado', 'metodo_pago', 'estado_pedido',
       'dias_entrega', 'calificacion', 'devuelto'],
      dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1849 entries, 0 to 1848
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_pedido         1849 non-null   object
 1   fecha             1836 non-null   object
 2   hora              1837 non-null   object
 3   id_cliente        1846 non-null   object
 4   segmento_cliente  1837 non-null   object
 5   ciudad            1831 non-null   object
 6   departamento      1833 non-null   object
 7   canal_venta       1842 non-null   object
 8   producto          1822 non-null   object
 9   categoria         1830 non-null   object
 10  cantidad          1842 non-null   object
 11  precio_unitario   1822 non-null   object
 12  descuento_pct     1835 non-null   object
 13  costo_envio       1838 non-null   object
 14  subtotal          1849 non-null   int64
 15  total_pagado      1849 non-null   float64
 16  metodo_pago       1829 non-null   object
 17  estado_pedido     1849 non-null   object
 18  dias_entrega      1243 non-null   object
 19  calificacion      1243 non-null   object
 20  devuelto          1847 non-null   object
dtypes: float64(1), int64(1), object(19)
memory usage: 303.5+ KB

In [13]:
df.describe(include="all")

,id_pedido,fecha,hora,id_cliente,segmento_cliente,ciudad,departamento,canal_venta,producto,categoria,...,precio_unitario,descuento_pct,costo_envio,subtotal,total_pagado,metodo_pago,estado_pedido,dias_entrega,calificacion,devuelto
count,1849,1836,1837,1846,1837,1831,1833,1842,1822,1830,...,1822,1835,1838,1.849000e+03,1.849000e+03,1829,1849,1243,1243,1847
unique,1800,259,874,817,17,23,12,19,46,5,...,123,25,19,NaN,NaN,24,16,29,21,14
top,ORD-00133,2026-08-14,06:36,CLI-00004,Corporativo,Villavicencio,Meta,Marketplace,Audífonos Bluetooth,Tecnología,...,74000,0,0,NaN,NaN,PSE,Entregado,4.0,5.0,No
freq,2,17,8,8,468,179,179,481,94,683,...,53,1075,451,NaN,NaN,334,1123,284,521,1742
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.534413e+05,1.878357e+05,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.386511e+05,5.506267e+05,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.700000e+04,-5.000000e+03,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,7.400000e+04,7.650000e+04,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.180000e+05,1.160000e+05,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.680000e+05,1.700000e+05,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.928000e+06,9.999999e+06,NaN,NaN,NaN,NaN,NaN

In [14]:
df.isnull().sum().sort_values(ascending=False)

dias_entrega        606
calificacion        606
producto             27
precio_unitario      27
metodo_pago          20
categoria            19
ciudad               18
departamento         16
descuento_pct        14
fecha                13
segmento_cliente     12
hora                 12
costo_envio          11
cantidad              7
canal_venta           7
id_cliente            3
devuelto              2
id_pedido             0
subtotal              0
total_pagado          0
estado_pedido         0
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(21)

In [16]:
df["id_pedido"].duplicated().sum()

np.int64(49)

In [18]:
ids_repetidos = df[df["id_pedido"].duplicated(keep=False)]
ids_repetidos.sort_values("id_pedido").head(20)

,id_pedido,fecha,hora,id_cliente,segmento_cliente,ciudad,departamento,canal_venta,producto,categoria,...,precio_unitario,descuento_pct,costo_envio,subtotal,total_pagado,metodo_pago,estado_pedido,dias_entrega,calificacion,devuelto
17,ORD-00018,2026-07-01,16:00,CLI-00331,Recurrente,Cali,Valle del Cauca,App móvil,Organizador modular,Hogar,...,63000,20,0,63000,50400.0,PSE,Entregado,3.0,4.0,No
1800,ORD-00018,2026-07-01,16:00,CLI-00331,Recurrente,Cali,Valle del Cauca,App móvil,Organizador modular,Hogar,...,63000,20,0,63000,50400.0,PSE,Entregado,3.0,4.0,No
1838,ORD-00089,2026-05-27,11:08,CLI-00113,Recurrente,Bucaramanga,Santander,App móvil,Teclado mecánico,Tecnología,...,165000,20,15000,165000,9999.0,PSE,Entregado,5.0,5.0,No
88,ORD-00089,2026-05-27,11:08,CLI-00113,Recurrente,Bucaramanga,Risaralda,App móvil,Teclado mecánico,Tecnología,...,165000,20,15000,165000,147000.0,PSE,Entregado,5.0,5.0,No
116,ORD-00117,2026-02-02,22:55,CLI-00408,Corporativo,Cali,Valle del Cauca,Marketplace,Secador de cabello,Cuidado personal,...,152000,0,0,152000,152000.0,Tarjeta débito,Entregado,4.0,5.0,No
1826,ORD-00117,2026-02-02,22:55,CLI-00408,Corporativo,Cali,Valle del Cauca,Marketplace,Secador de cabello,Cuidado personal,...,152000,0,0,152000,152000.0,Tarjeta débito,Entregado,4.0,5.0,No
130,ORD-00131,2026-03-11,10:24,CLI-00246,Recurrente,Medellín,Tolima,Web,Juego de sábanas,Hogar,...,109000,0,8000,109000,117000.0,Contraentrega,Enviado,NaN,NaN,No
1808,ORD-00131,2026-03-11,10:24,CLI-00246,Recurrente,Medellín,Antioquia,Web,Juego de sábanas,Hogar,...,109000,0,8000,109000,117000.0,Contraentrega,Enviado,NaN,NaN,No
132,ORD-00133,2026-07-12,09:23,CLI-00715,Recurrente,Bogotá,Cundinamarca,Web,Secador de cabello,Cuidado personal,...,158000,20,15000,158000,141400.0,PSE,Entregado,7.0,3.0,No
1816,ORD-00133,2026-07-12,09:23,CLI-00715,Recurrente,Bogotá,Cundinamarca,Web,Secador de cabello,Cuidado personal,...,158000,20,15000,158000,141400.0,PSE,Entregado,7.0,3.0,No
230,ORD-00231,NaN,09:41,CLI-00511,Corporativo,Pereira,Risaralda,Instagram,Kit de barbería,Cuidado personal,...,129000,25,8000,258000,201500.0,Tarjeta débito,Entregado,7.0,3.0,No
1828,ORD-00231,NaN,09:41,CLI-00511,Corporativo,Pereira,Risaralda,Instagram,Kit de barbería,Cuidado personal,...,129000,25,8000,258000,201500.0,Tarjeta débito,Entregado,7.0,3.0,No
1832,ORD-00240,2026-08-03,12:37,CLI-00448,VIP,Bogotá,Cundinamarca,App móvil,Secador de cabello,Cuidado personal,...,155000,10,0,155000,139500.0,Tarjeta crédito,entregado,6.0,2.0,No
239,ORD-00240,2026-08-03,12:37,CLI-00448,VIP,Bogotá,Cundinamarca,App móvil,Secador de cabello,Cuidado personal,...,155000,10,0,155000,139500.0,Tarjeta crédito,Entregado,6.0,2.0,x
299,ORD-00300,2026-02-03,16:04,CLI-00103,Corporativo,Barranquilla,Atlántico,App móvil,Silla ergonómica,Oficina,...,485000,10,0,485000,436500.0,Tarjeta crédito,Entregado,8.0,4.0,No
1825,ORD-00300,2026-02-03,16:04,CLI-00103,Corporativo,Barranquilla,Atlántico,App móvil,Silla ergonómica,Oficina,...,485000,10,0,485000,436500.0,Tarjeta crédito,Entregado,8.0,4.0,No
1814,ORD-00329,2026-07-06,06:58,CLI-00478,Recurrente,Villavicencio,Meta,Marketplace,Botella térmica,Hogar,...,62000,0,15000,62000,77000.0,PSE,Entregado,7.0,3.0,No
328,ORD-00329,2026-07-06,06:58,CLI-00478,Recurrente,Villavicencio,Meta,Marketplace,Botella térmica,Hogar,...,62000,0,15000,62000,77000.0,PSE,Entregado,7.0,3.0,No
1821,ORD-00335,2026-02-13,20:58,CLI-00771,VIP,Pereira,Risaralda,App móvil,Silla ergonómica,Oficina,...,485000,15,15000,485000,427250.0,PSE,Entregado,4.0,1.0,No
334,ORD-00335,2026-02-13,20:58,CLI-00771,VIP,Pereira,Risaralda,App móvil,Silla ergonómica,Oficina,...,485000,15,15000,485000,427250.0,PSE,Entregado,4.0,1.0,No

In [19]:
df[df.duplicated(keep=False)].sort_values("id_pedido").head(20)

,id_pedido,fecha,hora,id_cliente,segmento_cliente,ciudad,departamento,canal_venta,producto,categoria,...,precio_unitario,descuento_pct,costo_envio,subtotal,total_pagado,metodo_pago,estado_pedido,dias_entrega,calificacion,devuelto
17,ORD-00018,2026-07-01,16:00,CLI-00331,Recurrente,Cali,Valle del Cauca,App móvil,Organizador modular,Hogar,...,63000,20,0,63000,50400.0,PSE,Entregado,3.0,4.0,No
1800,ORD-00018,2026-07-01,16:00,CLI-00331,Recurrente,Cali,Valle del Cauca,App móvil,Organizador modular,Hogar,...,63000,20,0,63000,50400.0,PSE,Entregado,3.0,4.0,No
116,ORD-00117,2026-02-02,22:55,CLI-00408,Corporativo,Cali,Valle del Cauca,Marketplace,Secador de cabello,Cuidado personal,...,152000,0,0,152000,152000.0,Tarjeta débito,Entregado,4.0,5.0,No
1826,ORD-00117,2026-02-02,22:55,CLI-00408,Corporativo,Cali,Valle del Cauca,Marketplace,Secador de cabello,Cuidado personal,...,152000,0,0,152000,152000.0,Tarjeta débito,Entregado,4.0,5.0,No
1816,ORD-00133,2026-07-12,09:23,CLI-00715,Recurrente,Bogotá,Cundinamarca,Web,Secador de cabello,Cuidado personal,...,158000,20,15000,158000,141400.0,PSE,Entregado,7.0,3.0,No
132,ORD-00133,2026-07-12,09:23,CLI-00715,Recurrente,Bogotá,Cundinamarca,Web,Secador de cabello,Cuidado personal,...,158000,20,15000,158000,141400.0,PSE,Entregado,7.0,3.0,No
230,ORD-00231,NaN,09:41,CLI-00511,Corporativo,Pereira,Risaralda,Instagram,Kit de barbería,Cuidado personal,...,129000,25,8000,258000,201500.0,Tarjeta débito,Entregado,7.0,3.0,No
1828,ORD-00231,NaN,09:41,CLI-00511,Corporativo,Pereira,Risaralda,Instagram,Kit de barbería,Cuidado personal,...,129000,25,8000,258000,201500.0,Tarjeta débito,Entregado,7.0,3.0,No
1825,ORD-00300,2026-02-03,16:04,CLI-00103,Corporativo,Barranquilla,Atlántico,App móvil,Silla ergonómica,Oficina,...,485000,10,0,485000,436500.0,Tarjeta crédito,Entregado,8.0,4.0,No
299,ORD-00300,2026-02-03,16:04,CLI-00103,Corporativo,Barranquilla,Atlántico,App móvil,Silla ergonómica,Oficina,...,485000,10,0,485000,436500.0,Tarjeta crédito,Entregado,8.0,4.0,No
328,ORD-00329,2026-07-06,06:58,CLI-00478,Recurrente,Villavicencio,Meta,Marketplace,Botella térmica,Hogar,...,62000,0,15000,62000,77000.0,PSE,Entregado,7.0,3.0,No
1814,ORD-00329,2026-07-06,06:58,CLI-00478,Recurrente,Villavicencio,Meta,Marketplace,Botella térmica,Hogar,...,62000,0,15000,62000,77000.0,PSE,Entregado,7.0,3.0,No
334,ORD-00335,2026-02-13,20:58,CLI-00771,VIP,Pereira,Risaralda,App móvil,Silla ergonómica,Oficina,...,485000,15,15000,485000,427250.0,PSE,Entregado,4.0,1.0,No
1821,ORD-00335,2026-02-13,20:58,CLI-00771,VIP,Pereira,Risaralda,App móvil,Silla ergonómica,Oficina,...,485000,15,15000,485000,427250.0,PSE,Entregado,4.0,1.0,No
369,ORD-00370,2026-01-31,21:18,CLI-00041,Nuevo,Manizales,Caldas,Instagram,Kit de barbería,Cuidado personal,...,135000,5,15000,135000,143250.0,Daviplata,Entregado,7.0,5.0,No
1820,ORD-00370,2026-01-31,21:18,CLI-00041,Nuevo,Manizales,Caldas,Instagram,Kit de barbería,Cuidado personal,...,135000,5,15000,135000,143250.0,Daviplata,Entregado,7.0,5.0,No
449,ORD-00450,NaN,11:46,CLI-00862,VIP,Pereira,Risaralda,Marketplace,Parlante portátil,Tecnología,...,150000,0,10000,150000,160000.0,Contraentrega,Entregado,3.0,4.0,No
1802,ORD-00450,NaN,11:46,CLI-00862,VIP,Pereira,Risaralda,Marketplace,Parlante portátil,Tecnología,...,150000,0,10000,150000,160000.0,Contraentrega,Entregado,3.0,4.0,No
1807,ORD-00490,2026-02-01,06:01,CLI-00502,Nuevo,Medellín,Antioquia,App móvil,Parlante portátil,Tecnología,...,148000,0,10000,148000,158000.0,Tarjeta débito,Enviado,NaN,NaN,No
489,ORD-00490,2026-02-01,06:01,CLI-00502,Nuevo,Medellín,Antioquia,App móvil,Parlante portátil,Tecnología,...,148000,0,10000,148000,158000.0,Tarjeta débito,Enviado,NaN,NaN,No